<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Tape_Player</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>TapeCassette.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ABC.png" />
    <None Remove="BackgroundCircleCovers.png" />
    <None Remove="BlockM2.png" />
    <None Remove="CenterBar.png" />
    <None Remove="Fillercolor.png" />
    <None Remove="FillerColor2.png" />
    <None Remove="Lines.png" />
    <None Remove="LineTrans.png" />
    <None Remove="New Project %281%29.png" />
    <None Remove="New Project.png" />
    <None Remove="new.png" />
    <None Remove="NeWFileTAPE.png" />
    <None Remove="NewFilmTapeBail.png" />
    <None Remove="NewFilmTapeBailBrown.png" />
    <None Remove="NewWheel.png" />
    <None Remove="OrignalBackgroundEdit.png" />
    <None Remove="Screenshot_3.png" />
    <None Remove="SQDarkblue %281%29.png" />
    <None Remove="Tape207.png" />
    <None Remove="TapeDeckUsE.png" />
    <None Remove="TapeStrechFinal.png" />
    <None Remove="WHEEL %281%29.png" />
    <None Remove="WheelBevelDown.png" />
    <None Remove="WheelCircleFinal.png" />
    <None Remove="WheelDownMore.png" />
    <None Remove="WheelHalf.png" />
    <None Remove="WheelRecessed.png" />
    <None Remove="WheelRecessedBlackLine.png" />
    <None Remove="WheelSmall.png" />
    <None Remove="WHEELSMALLFINAL.png" />
    <None Remove="WHEELSMALLFINALBULB.png" />
    <None Remove="WheelSmallReally.png" />
    <None Remove="WheelSymtrical.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Y_noaudio.mp4;YT_noaudio.mp4;R_noaudio.mp4;O_noaudio.mp4;F_noaudio.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="song.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="60minTape.mp3;90minTape.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="BlankCassette.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Cassetttes\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sfx\**\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
    <Import Include="System.Windows.Shapes" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="TapeCassette.ico" />
    <Resource Include="ABC.png" />
    <Resource Include="BackgroundCircleCovers.png" />
    <Resource Include="BlockM2.png" />
    <Resource Include="CenterBar.png" />
    <Resource Include="Fillercolor.png" />
    <Resource Include="FillerColor2.png" />
    <Resource Include="Lines.png" />
    <Resource Include="LineTrans.png" />
    <Resource Include="New Project (1).png" />
    <Resource Include="New Project.png" />
    <Resource Include="new.png" />
    <Resource Include="NeWFileTAPE.png" />
    <Resource Include="NewFilmTapeBail.png" />
    <Resource Include="NewFilmTapeBailBrown.png" />
    <Resource Include="NewWheel.png" />
    <Resource Include="OrignalBackgroundEdit.png" />
    <Resource Include="Screenshot_3.png" />
    <Resource Include="SQDarkblue (1).png" />
    <Resource Include="Tape207.png" />
    <Resource Include="TapeDeckUsE.png" />
    <Resource Include="TapeStrechFinal.png" />
    <Resource Include="WHEEL (1).png" />
    <Resource Include="WheelBevelDown.png" />
    <Resource Include="WheelCircleFinal.png" />
    <Resource Include="WheelDownMore.png" />
    <Resource Include="WheelHalf.png" />
    <Resource Include="WheelRecessed.png" />
    <Resource Include="WheelRecessedBlackLine.png" />
    <Resource Include="WheelSmall.png" />
    <Resource Include="WHEELSMALLFINAL.png" />
    <Resource Include="WHEELSMALLFINALBULB.png" />
    <Resource Include="WheelSmallReally.png" />
    <Resource Include="WheelSymtrical.png" />
  </ItemGroup>

</Project>
